#!/bin/bash

TZS=(America/Los_Angeles America/Chicago America/New_York Europe/Budapest UTC)

DATE="${1:-now}"
shift

print_dates() {
  for TZ in "" "${TZS[@]}"; do
    if [ -z "$TZ" ]; then
      echo -n "local: "
    else
      echo -n "$TZ: "
    fi
    TZ=$TZ date --date "$DATE" -Iminutes "$@"
  done
}

print_dates "$@" | column -t
