#!/bin/sh
# Commit current state of working tree
set -e

git add --all .

# From etckeeper commit.d/50vcs-commit
hostname=$(hostname)
dnsdomainname=$(dnsdomainname 2>/dev/null || true)
if [ -n "$dnsdomainname" ]; then
    hostname="$hostname.$dnsdomainname"
fi

if [ -z "$GIT_COMMITTER_EMAIL" ]; then
    GIT_COMMITTER_EMAIL=$(whoami)"@$hostname"
    export GIT_COMMITTER_EMAIL
fi

# Commit changes (supress "nothing to commit" message if there are no changes)
# Git exits with 1 if there is nothing to commit
git commit --quiet -m "Auto commit" >/dev/null || true
