#!/usr/bin/env bash

# TODO: blkid returns inconsistent results without sudo. After using sudo, the
# new results seem to be cached.
#
# $ blkid -o value -s UUID /dev/sdb2
# d937b8ba-4fc8-4d23-be2b-8183413fc28e
# $ sudo blkid -o value -s UUID /dev/sdb2
# [sudo] password for svend:
# dd8e4e10-8b7a-480c-ac41-353a94e6ea76
# $ blkid -o value -s UUID /dev/sdb2
# dd8e4e10-8b7a-480c-ac41-353a94e6ea76

set -e

is_uuid()
{
  expr "$1" : '\w\{8\}-\w\{4\}-\w\{4\}-\w\{4\}-\w\{12\}$' >/dev/null
}

cmd_close()
{
  if is_uuid "$1"; then
    UUID=$1
    DEV=$(sudo blkid -U "$UUID")
  else
    DEV=$1
    UUID=$(sudo blkid -o value -s UUID "$DEV")
  fi

  udisksctl unmount --block-device "/dev/mapper/luks-$UUID" || true
  udisksctl lock --block-device "$DEV"
}

cmd_open()
{
  if is_uuid "$1"; then
    UUID=$1
    DEV=$(sudo blkid -U "$UUID")
  else
    DEV=$1
    UUID=$(sudo blkid -o value -s UUID "$DEV")
  fi
  KEY=$2

  case "$KEY" in
  -)
    key_cmd="cat"
    ;;
  *.gpg)
    key_cmd="gpg -d -q \"$KEY\""
    ;;
  *)
    key_cmd="cat \"$KEY\""
  esac

  udisksctl unlock --block-device "$DEV" --key-file <(eval "$key_cmd") || true
  udisksctl mount --block-device "/dev/mapper/luks-$UUID"
}

cmd_format()
{
  if is_uuid "$1"; then
    UUID=$1
    DEV=$(sudo blkid -U "$UUID")
  else
    DEV=$1
    # luksFormat changes the partition UUID
  fi
  KEY=$2

  head -c 256 /dev/random | gpg -e > "$KEY"

  gpg -d -q "$KEY" | sudo cryptsetup --key-file - luksFormat "$DEV"
  # luksFormat changes the partition UUID
  UUID=$(sudo blkid -o value -s UUID "$DEV")

  gpg -d -q "$KEY" |
    sudo cryptsetup --key-file - luksOpen "$DEV" "luks-uuid-$UUID"
  sudo mkfs.ext4 "/dev/mapper/luks-uuid-$UUID"
}

case "$1" in
close|format|open)
  command=$1
  ;;
*)
  echo "Usage: $0 open <device|UUID> <keyfile>" >&2
  echo "Usage: $0 close <device|UUID>" >&2
  echo "Usage: $0 format <device|UUID> <keyfile>" >&2
  exit 3
  ;;
esac
shift

"cmd_$command" "$@"
