#!/usr/bin/env python3

import argparse
import json
import sys
import yaml


def walk(prefix, val):
    if isinstance(val, dict):
        for k, v in val.items():
            walk(prefix + [k], v)
    elif isinstance(val, list):
        for i, v in enumerate(val):
            iprefix = prefix.copy()
            iprefix[-1] += f"[{i}]"
            walk(iprefix, v)
    else:
        path = ".".join(prefix)
        qval = json.dumps(val)
        print(f"{path}: {qval}")



parser = argparse.ArgumentParser()
parser.add_argument("--format", choices={"json", "yaml"}, default="json")
args = parser.parse_args()

if args.format == "json":
    data = json.load(sys.stdin)
    walk([""], data)
elif args.format == "yaml":
    for data in yaml.safe_load_all(sys.stdin):
        print("---")
        walk([""], data)
