#!/bin/sh
set -e

HOST=$1
shift

rsync \
  --recursive \
  --update \
  --verbose \
  --exclude .aux \
  --exclude thumbnails \
  "$@" \
  $HOST:'/storage/*/DCIM/Camera/' \
  $HOME/media/photos/$HOST
