#!/usr/bin/env bash

set -euf -o pipefail

TARGET=$1
CERT=$2
KEY=$3

scp "$CERT" "$TARGET":
scp "$KEY" "$TARGET":

# Import new certificate
ssh "$TARGET" "/certificate/remove server-new" || true
ssh "$TARGET" "/certificate/import name=server-new file-name=$(basename $CERT) passphrase=\"\""
ssh "$TARGET" "/file/remove $(basename $CERT)"
ssh "$TARGET" "/certificate/import name=server-new file-name=$(basename $KEY) passphrase=\"\""
ssh "$TARGET" "/file/remove $(basename $KEY)"

# Point to new certificate
ssh "$TARGET" "/ip/service/set www-ssl certificate=server-new disabled=no tls-version=only-1.2"
ssh "$TARGET" "/ip/service/set api-ssl certificate=server-new disabled=no tls-version=only-1.2"

# Move old certificate
ssh "$TARGET" "/certificate/remove server-old" || true
ssh "$TARGET" "/certificate/set server name=server-old"

# Rename new certificate
ssh "$TARGET" "/certificate/set server-new name=server"

ssh "$TARGET" "/certificate/print detail"
